### ISSUE TITLE
create a notebook server to support Knowledge Graph session

### ISSUE THREAD

**Issue by ctb** [nih-cfde/2022-may-hackathon#4]
starting with a binder; Ben Stear said:

>I think the only extra package we’ll need besides from an installation of python 3 is the `requests` library

working on this here - https://github.com/nih-cfde/2022-may-kg-binder - starting with a binder.

to run (off of stable branch, not main):

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/nih-cfde/2022-may-kg-binder/stable)

**Comment by ctb** [comment]
victory!

<img width="885" alt="Screen Shot 2022-04-29 at 10 37 04 AM" src="https://user-images.githubusercontent.com/51016/165995079-de8ea675-1b88-4140-b536-6ae27c6de9bf.png">

**Comment by benstear** [comment]
thank you!
